# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'GTXSample' do
  pod 'GTXiLib', :path => '../'

  target 'GTXSampleTests' do
    inherit! :search_paths
  end

  target 'GTXSampleUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|        
    target.build_configurations.each do |config|  
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'

      if target.name == "GTXiLib"
        config.build_settings['HEADER_SEARCH_PATHS'] = '$(SRCROOT)'
        config.build_settings['VERSIONING_SYSTEM'] = 'none'
      end
    end
  end
end
